apiVersion: v1
kind: ConfigMap
metadata:
  name: web-configmap
  labels:
  {{- include "web.labels" . | nindent 4 }}
data:
  {{- if .Values.web.environment }}
  {{- range $key, $val := .Values.web.environment }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- end }}
  PORT: '3000'
  AUTH_SERVER_URL: https://auth.susimsek.github.io
  OAUTH2_CLIENT_ID: web-client
  OAUTH2_CLIENT_SECRET: '123456'