apiVersion: v1
kind: Secret
metadata:
  name: oauth2-client-secret
  labels:
    {{- include "web.labels" . | nindent 4 }}
type: Opaque
data:
  OAUTH2_CLIENT_ID: {{ .Values.web.auth.clientId | b64enc | quote }}
  OAUTH2_CLIENT_SECRET: {{ .Values.web.auth.clientSecret | b64enc | quote }}