server:
  port: ${PORT:8081}

spring:
  cloud:
    vault:
      enabled: false
    consul:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://test_user123456:4hRsOKoJxkHswunQ@cluster0.nbzfi.mongodb.net/demo
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  security:
    oauth2:
     resource-server:
       jwt:
         issuer-uri: http://localhost:9000
  redis:
    host: redis-11596.c240.us-east-1-3.ec2.cloud.redislabs.com
    port: 11596
    database: 0
    password: G9Ny5o87hnEpO9RiRQeYHUNFFl8vDSP3

cache:
    expiration: 5m

logging:
  level:
    ROOT: DEBUG
    io.github.susimsek.product: DEBUG
  use-json-format: false
  logstash:
    enabled: false
    host: localhost
    port: 5001
    ring-buffer-size: 512
