server:
  shutdown: graceful
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
      database: ${SPRING_DATA_MONGODB_DATABASE:product}
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCE-SERVER_JWT_ISSUER-URI:http://localhost:9000}
  redis:
    host: ${SPRING_REDIS_HOST:localhost}
    port: ${SPRING_REDIS_PORT:6379}
    database: ${SPRING_REDIS_DATABASE:0}
    password: ${SPRING_REDIS_PASSWORD:d41d8cd98f00b204e9800998ecf8427e}

cache:
  expiration: ${CACHE_EXPIRATION:3600s}

logging:
  level:
    ROOT: INFO
    io.github.susimsek.product: INFO
  use-json-format: false
  logstash:
    enabled: ${LOGSTASH_ENABLED:true}
    host: ${LOGSTASH_HOST:localhost}
    port: ${LOGSTASH_PORT:5000}
    ring-buffer-size: ${LOGSTASH_RING_BUFFER_SIZE:512}