version: 2.1

orbs:
  snyk: snyk/snyk@1.2.3

jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:16-buster
        auth:
          username: $DOCKER_REGISTRY_USERNAME
          password: $DOCKER_REGISTRY_PASSWORD
    working_directory: ~/app
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json"" }}
      - run:
          name: Print Node Version
          command: node -v
      - run:
          name: Print NPM Version
          command: npm -v
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: low
          token-variable: SNYK_TOKEN
      - run:
          name: Quality Analysis
          command: npm run sonar
      - run:
          name: Publish Docker
          command: |
            TAG=latest
            docker build -t suayb/apollo-gateway:$TAG .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push suayb/apollo-gateway:$TAG