server:
  port: ${PORT:9000}

spring:
  cloud:
    vault:
      enabled: false
    consul:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://test_user123456:4hRsOKoJxkHswunQ@cluster0.nbzfi.mongodb.net/auth
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false

auh-server:
  provider:
   issuer: http://localhost:9000

token:
  access-token-time-to-live: 1d
  refresh-token-time-to-live: 1d

logging:
  level:
    ROOT: DEBUG
    io.github.susimsek.auth: DEBUG
  use-json-format: false
  logstash:
    enabled: false
    host: localhost
    port: 5001
    ring-buffer-size: 512