server:
  shutdown: graceful
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27018}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
      database: ${SPRING_DATA_MONGODB_DATABASE:auth}
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false

auth-server:
  provider:
    issuer: ${AUTH-SERVER_PROVIDER_ISSUER:http://auth-service:8080}

logging:
  level:
    ROOT: INFO
    io.github.susimsek.auth: INFO
  use-json-format: false
  logstash:
    enabled: ${LOGSTASH_ENABLED:true}
    host: ${LOGSTASH_HOST:localhost}
    port: ${LOGSTASH_PORT:5000}
    ring-buffer-size: ${LOGSTASH_RING_BUFFER_SIZE:512}