server:
  shutdown: graceful
  port: ${PORT:8080}

spring:
  data:
    mongodb:
      host: ${SPRING_DATA_MONGODB_HOST:localhost}
      port: ${SPRING_DATA_MONGODB_PORT:27017}
      authentication-database: ${SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE:admin}
      database: ${SPRING_DATA_MONGODB_DATABASE:review}
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: ${SPRING_SECURITY_OAUTH2_RESOURCE-SERVER_JWT_ISSUER-URI:http://localhost:9000}
