server:
  port: ${PORT:8082}

spring:
  cloud:
    vault:
      enabled: false
    consul:
      enabled: false
  data:
    mongodb:
      uri: mongodb+srv://test_user123456:4hRsOKoJxkHswunQ@cluster0.nbzfi.mongodb.net/demo
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: false
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000
  redis:
    host: localhost
    port: 6379
    database: 0
    password: d41d8cd98f00b204e9800998ecf8427e

  cache:
    expiration: 5m

logging:
  level:
    ROOT: DEBUG
    io.github.susimsek.review: DEBUG
  use-json-format: false
  logstash:
    enabled: false
    host: localhost
    port: 5001
    ring-buffer-size: 512
