version: 2.1

orbs:
  snyk: snyk/snyk@1.2.3

aliases:
  - &maven-settings-file
      "\"<settings xmlns='http://maven.apache.org/SETTINGS/1.2.0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
      xsi:schemaLocation='http://maven.apache.org/SETTINGS/1.2.0 http://maven.apache.org/xsd/settings-1.2.0.xsd'>
      <servers>
      <server>
      <username>$GITHUB_USERNAME</username>
      <password>$GITHUB_PASSWORD</password>
      <id>github</id>
      </server>
      <server>
      <username>$DOCKER_REGISTRY_USERNAME</username>
      <password>$DOCKER_REGISTRY_PASSWORD</password>
      <id>registry-1.docker.io</id>
      </server>
      <server>
      <username>$HEROKU_USERNAME</username>
      <password>$HEROKU_API_KEY</password>
      <id>registry.heroku.com</id>
      </server>
      </servers>
      </settings>\""
commands:
  generate-maven-settings-file:
    parameters:
      settings-file:
        type: string
    steps:
      - run:
          name: Generate Maven Settings File
          command: |
            mkdir -p ~/.m2
            echo -e << parameters.settings-file >> > ~/.m2/settings.xml

jobs:
  build:
    machine:
      image: ubuntu-2204:2022.07.1
      docker_layer_caching: true
    working_directory: ~/repo/auth-service
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/repo
      - generate-maven-settings-file:
          settings-file: *maven-settings-file
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Print Java Version
          command: java -version
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - run:
          name: Install Dependencies
          command: mvn dependency:go-offline
      - snyk/scan:
          fail-on-issues: false
          monitor-on-build: true
          severity-threshold: low
          token-variable: SNYK_TOKEN
      - run:
          name: Test
          command: mvn -ntp clean verify
      - run:
          name: Packaging
          command: mvn -ntp package -DskipTests
      - run:
          name: Quality Analysis
          command: mvn -ntp -Psonar initialize sonar:sonar -Dsonar.login=$SONAR_TOKEN
      - run:
          name: Publish Docker
          command: mvn -ntp -Pjib jib:build -DskipTests