global:
  name: consul
  datacenter: dc1
  acls:
    manageSystemACLs: false
  tls:
    enabled: false
server:
  replicas: 1
  bootstrapExpect: 1
  disruptionBudget:
    maxUnavailable: 0
  storage: 75M

client:
  enabled: true

